### ISSUE TITLE
Not worked

### ISSUE THREAD

**Issue by vitalii-avd** [0x-DLN/obsidian-table-checkboxes#11]
I don't know what's the reason, but the plugin isn't working for me. 

I installed it through the store, restarted Obsidian, tried to test it, and... nothing.

I only have 4 plugins installed and only one of them is active (besides the checkbox in the table).

There's no substitution of HTML tags in the table.

Obsidian version 1.5.11.

---

![01](https://github.com/DylanGiesberts/obsidian-table-checkboxes/assets/154265894/135ad45e-f86c-4654-98e8-d10143d6e55f)
![02](https://github.com/DylanGiesberts/obsidian-table-checkboxes/assets/154265894/1b12aa67-53fb-422a-a6ad-229097694858)

**Comment by DylanGiesberts** [comment]
Can you try version 2.0.8 from [here](https://github.com/DylanGiesberts/obsidian-table-checkboxes/releases/download/2.0.8/main.js)? You need to replace the main.js file in your current plugin folder. You can open the plugin folder from Obsidian and drag the file into `obsidian-table-checkboxes`.

If that doesn't solve your issue, can you fill in the following:

- Obsidian version: 
- Plugin version: 
- Windows keyboard language:

**Comment by LennartCode** [comment]
This is still the case for

- Windows 10
- Obsidian 1.7.7 (latest as of writing)
- Plugin version 2.0.8 (latest as of writing)
- No other table plugins installed
- Independent of bracket completion setting in Obsidian
- Does work neither on manual typing nor copy-pasting
- Independent of keyboard (could not find version numbers)
  - Custom keyboard layout
  - German
  - English UK

**Comment by 0x-DLN** [comment]
Should be fixed in 3.0.0
