### ISSUE TITLE
Checkbox State Not Maintained?

### ISSUE THREAD

**Issue by ChristopherWSmith** [0x-DLN/obsidian-table-checkboxes#12]
First off, thank you for making this plugin!  It is a relief that I can now have checkboxes in my tables.  

I am having an issue related to the state of the checkbox, i.e. whether it is checked or not.  It seems like the html is not getting updated when the box becomes checked?  This is causing an issue with being able to sync the tables - if I check off a box on one device, the box still shows as unchecked on another device. 

Is this intentional?

**Comment by DylanGiesberts** [comment]
Can you double check if your checkboxes are in the correct format as described [here](https://github.com/DylanGiesberts/obsidian-table-checkboxes/issues/10#issuecomment-2029928471)?

Also, what version of Obsidian are you using?
