### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Ananas0631** [0x-DLN/obsidian-table-checkboxes#13]
I'll keep it short. I did everything as you described but when i print - [  ], normal checkbox appears and it is not readable with reading mode. The problem is i print - , okey [,okey, i press two spaces so now i have [  , allright, but when i close bracket html code doesn't appear. It continues as usual and i can't use checkbox with tables. I use the latest version both obsidian and plugin. Do you think where is the error?  

Might it be having trouble with other plugins?

**Comment by DylanGiesberts** [comment]
There should be 0 or 1 spaces between [ and ] for the checkbox to be replaced. If that doesn't solve it read below

---

Can you try version 2.0.8 from [here](https://github.com/DylanGiesberts/obsidian-table-checkboxes/releases/download/2.0.8/main.js)? You need to replace the main.js file in your current plugin folder. You can open the plugin folder from Obsidian and drag the file into `obsidian-table-checkboxes`.

If that doesn't solve your issue, can you fill in the following:

- Obsidian version: 
- Plugin version: 
- Windows keyboard language:

**Comment by Ananas0631** [comment]
> There should be 0 or 1 spaces between [ and ] for the checkbox to be replaced. If that doesn't solve it read below
> 
> ---
> 
> Can you try version 2.0.8 from [here](https://github.com/DylanGiesberts/obsidian-table-checkboxes/releases/download/2.0.8/main.js)? You need to replace the main.js file in your current plugin folder. You can open the plugin folder from Obsidian and drag the file into `obsidian-table-checkboxes`.
> 
> If that doesn't solve your issue, can you fill in the following:
> 
> - Obsidian version: 
> - Plugin version: 
> - Windows keyboard language: 

https://github.com/DylanGiesberts/obsidian-table-checkboxes/assets/77831170/30749863-1a6f-46d6-ae65-9d68f63e6a41

**Comment by 0x-DLN** [comment]
Should be fixed in 3.0.0, please open a new issue if you still run into any bugs
