### ISSUE TITLE
unable to press press the checkbox. The html code just shows up instead

### ISSUE THREAD

**Issue by sreesankar711** [0x-DLN/obsidian-table-checkboxes#15]
i have a simple table

![image](https://github.com/DylanGiesberts/obsidian-table-checkboxes/assets/100954808/714303ce-c8e4-4903-a3a6-cbd11c2825ca)

so here the checkbox is created directly by this extension with the snippet
```
<input type="checkbox" unchecked id="b80aa5">
```

even tho it renders properly, it is un clickable. when i try to click the box in live preview, it changes to 
![image](https://github.com/DylanGiesberts/obsidian-table-checkboxes/assets/100954808/2780d6ef-16ed-49a6-8404-eb34bda78fc5)

i am able to check and uncheck the checkbox in readonly mode, but it makes life difficult. hope so one will look into it.

**Comment by DylanGiesberts** [comment]
Hi, this is because of live preview mode while editing.

Don't really have time to fix right now, as a workaround it should work as expected in view mode (click the book top right, or hit `ctrl`+`e` or `⌘`+`e`)

**Comment by sreesankar711** [comment]
Hey,
Just take your time to fix this. I will leave this issue open until then so others may see it.
Might be better if u could update the readme. Section - How to use
