### ISSUE TITLE
Regenerate ID when copy-pasting checkboxes

### ISSUE THREAD

**Issue by Lavaeolous** [0x-DLN/obsidian-table-checkboxes#16]
Currently, selecting a checkbox and copying it into a new cell copies the content as-is.
It would be a very helpful addition to trigger the generation of a new id when an existing checkbox is pasted into the same document.

Alternatively a function to regenerate the id's on all checkboxes in the current document would work as well.

My use-case is tracking campaign preparation for a rpg:
![image](https://github.com/DylanGiesberts/obsidian-table-checkboxes/assets/14833806/04a4a24b-fc97-4fb2-bbe6-2d073c363c72)

Entering that many checkboxes manually is not fun, so i'm looking for easier ways.

**Comment by NelanaPrime** [comment]
Although it's not a solution, a workaround I've found is to use keyboard macros to quickly input the textbox notation.
Perhaps using a complex macro you could fully automate the creation of your checkboxes, at least until a solution is built into the plugin.

**Comment by 0x-DLN** [comment]
A command to regenerate checkbox ID's has been added to 3.0.0, alongside some improvements to the automatic conversion
