### ISSUE TITLE
Support for multi-cursor

### ISSUE THREAD

**Issue by Amras2322** [0x-DLN/obsidian-table-checkboxes#17]
Hello!

As the title implies, would it be possible to add support for Obsidian's Multi-Cursor functionality? This way you can put check boxes in an entire table column, for example, instead of going down cell by cell.

**Comment by 0x-DLN** [comment]
While converting these automatically proved a bit too tricky, there's now a command in version 3.0.0 to mass-convert checkbox (including those outside of tables, optionally).
